### ISSUE TITLE
asp:ScriptManagerProxy can not be found

### ISSUE THREAD

**Issue by last-Programmer** [seanofw/Redesigner#3]
we are using ScriptManagerProxy aspx control and redesigner is not able to find that control.

we are getting this error
Line 2: Class for control <asp:ScriptManagerProxy> could not be loaded:
Value cannot be null.
Parameter name: key

**Comment by seanofw** [comment]
Sorry, I missed this posting.  Did you try it with the .NET 4.x branch?  The `master` branch was designed for .NET 2.x/3.x, but there is an experimental [.NET 4.x feature branch](https://github.com/seanofw/Redesigner/tree/branches/net40) that improves support for things like this.

**Comment by last-Programmer** [comment]
Thank You. the new branch solved the problem.
