### ISSUE TITLE
Redesigner is not able to load DLL from same folder

### ISSUE THREAD

**Issue by lostdev** [seanofw/Redesigner#4]
Hi,

I am trying Redesigner in my project and it's not able to load references from the same directory as the website, even if the file exists. See below:

![image](https://user-images.githubusercontent.com/1780922/55234958-adc08b80-5202-11e9-8513-ca87819a12c8.png)

I'd rather not have to add the assembly to the GAC. It takes a few seconds before it errors out.

This is a .NET 4.7 project, C#, it seemed to have found registered all the namespaces correctly, just cannot load the assembly:

![image](https://user-images.githubusercontent.com/1780922/55235127-21629880-5203-11e9-9434-a3f0ab8931f3.png)

Any help would be appreciated.

Thanks,
Carl

**Comment by seanofw** [comment]
My best guess says that maybe this is a .NET version-compatibility issue.  If your website is running on .NET Framework 4.x+ as it says it is, you should probably use the [`net40`](https://github.com/seanofw/Redesigner/tree/branches/net40) feature branch.  You'd get that kind of behavior if Redesigner itself was built for .NET 3.5 (still the default) but you were trying to use it on DLLs built for .NET 4.0.

**Comment by lostdev** [comment]
I should have followed up earlier; you are 100% correct. After filing this issue I rebuilt using 4.7.2 and was able to load the assemblies without any issues.

I did, however, run into additional issues which prevented me from using the tool. If this project is still active please let me know and I'll create new issues for what I found.

Thanks!

**Comment by seanofw** [comment]
It's somewhat active, in that every once in a while, a bug report comes in, and I fix it.  I probably won't have time to fix your issues for a few days, but I aim to fix every issue that gets reported in every project I maintain.

Feel free to report new issues as you find them.
